//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virgil.SDK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Virgil.SDK.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null or whitespace.
        /// </summary>
        internal static string ExceptionArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ExceptionArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain value specified for the domain identity is invalid.
        /// </summary>
        internal static string ExceptionDomainValueDomainIdentityIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionDomainValueDomainIdentityIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity verification request is not sent.
        /// </summary>
        internal static string ExceptionIdentityVerificationIsNotSent {
            get {
                return ResourceManager.GetString("ExceptionIdentityVerificationIsNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key pair with specified name is already exists..
        /// </summary>
        internal static string ExceptionKeyPairAlreadyExistsException {
            get {
                return ResourceManager.GetString("ExceptionKeyPairAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key pair is not found.
        /// </summary>
        internal static string ExceptionKeyPairNotFound {
            get {
                return ResourceManager.GetString("ExceptionKeyPairNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key pair parameters is not valid..
        /// </summary>
        internal static string ExceptionKeyPairParametersIsNotValid {
            get {
                return ResourceManager.GetString("ExceptionKeyPairParametersIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key is not found.
        /// </summary>
        internal static string ExceptionPublicKeyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPublicKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String can not be empty.
        /// </summary>
        internal static string ExceptionStringCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String parameter should have length less than {0}.
        /// </summary>
        internal static string ExceptionStringLengthIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionStringLengthIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data with same fields is already exists..
        /// </summary>
        internal static string ExceptionUserDataAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionUserDataAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data class specified is invalid.
        /// </summary>
        internal static string ExceptionUserDataClassSpecifiedIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionUserDataClassSpecifiedIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data confirmation entity not found.
        /// </summary>
        internal static string ExceptionUserDataConfirmationEntityNotFound {
            get {
                return ResourceManager.GetString("ExceptionUserDataConfirmationEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data confirmation identityInfo invalid.
        /// </summary>
        internal static string ExceptionUserDataConfirmationTokenInvalid {
            get {
                return ResourceManager.GetString("ExceptionUserDataConfirmationTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data integrity constraint violation.
        /// </summary>
        internal static string ExceptionUserDataIntegrityConstraintViolation {
            get {
                return ResourceManager.GetString("ExceptionUserDataIntegrityConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user data is not confirmed yet.
        /// </summary>
        internal static string ExceptionUserDataIsNotConfirmedYet {
            get {
                return ResourceManager.GetString("ExceptionUserDataIsNotConfirmedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data is not found.
        /// </summary>
        internal static string ExceptionUserDataNotFound {
            get {
                return ResourceManager.GetString("ExceptionUserDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user data value is required.
        /// </summary>
        internal static string ExceptionUserDataValueIsRequired {
            get {
                return ResourceManager.GetString("ExceptionUserDataValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data was already confirmed and does not need further confirmation.
        /// </summary>
        internal static string ExceptionUserDataWasAlreadyConfirmed {
            get {
                return ResourceManager.GetString("ExceptionUserDataWasAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user id had been confirmed earlier.
        /// </summary>
        internal static string ExceptionUserIdHadBeenConfirmed {
            get {
                return ResourceManager.GetString("ExceptionUserIdHadBeenConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info data validation failed.
        /// </summary>
        internal static string ExceptionUserInfoDataValidationFailed {
            get {
                return ResourceManager.GetString("ExceptionUserInfoDataValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Access Token is not provider..
        /// </summary>
        internal static string ExceptionVirgilServiceNotInitialized {
            get {
                return ResourceManager.GetString("ExceptionVirgilServiceNotInitialized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Access Token is not provider..
        /// </summary>
        internal static string ExceptionVirgilConfigIsNotInitialized
        {
            get
            {
                return ResourceManager.GetString("ExceptionVirgilConfigIsNotInitialized", resourceCulture);
            }
        }
    }
}
