//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virgil.SDK.Keys.Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Variables : global::System.Configuration.ApplicationSettingsBase {
        
        private static Variables defaultInstance = ((Variables)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Variables())));
        
        public static Variables Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"virgil_card\":{\"id\":\"daa70f1f-5ab7-4789-a9da-7de413b4acc9\",\"created_at\":\"2015-12" +
            "-21T10:52:56\",\"data\":{\"hello\":\"world\"},\"is_confirmed\":false,\"hash\":\"eyJpZCI6ImRh" +
            "YTcwZjFmLTVhYjctNDc4OS1hOWRhLTdkZTQxM2I0YWNjOSIsImNyZWF0ZWRfYXQiOiIyMDE1LTEyLTIx" +
            "IDEwOjUyOjU2IiwiZGF0YSI6eyJoZWxsbyI6IndvcmxkIn0sImlzX2NvbmZpcm1lZCI6ZmFsc2UsInB1" +
            "YmxpY19rZXlfaWQiOiIxNTlkMjBiMS05MTE1LTRlZmEtYmM1Ny1hMTM2MTk0NWYyZWMiLCJpZGVudGl0" +
            "eV9pZCI6ImUwMjExYmYxLTMxNGQtNDk5OC05ZmRiLWNjNDNiYjJiZjBiNCJ9\",\"public_key\":{\"id\"" +
            ":\"159d20b1-9115-4efa-bc57-a1361945f2ec\",\"created_at\":\"2015-12-21T10:52:56\",\"publ" +
            "ic_key\":\"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHYk1CUUdCeXFHU000OUFnRUdDU3NrQXd" +
            "NQ0NBRUJEUU9CZ2dBRWRBdjQ1V2dYYWpEU0VjclhHazFQcFZZNgp4Q1IxV1MxWTVSZ254eEdxVEkweHU" +
            "3azlOeCtpN2NsRVloVlF2TUgxd3RpWGtsSmw2R2FRTHUrMUhVbWJEMkkxCnRLUDQyRXFNQ2JSSGR3SzQ" +
            "5Nms2czZBRlZEN0x2WmVzQmJTQysxd014Vi9zUDlJWmhxTjhxL3hsUVkrN2hPYU8KdkxEWmJJeFc2TVB" +
            "xdkxHYjdPUT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==\"},\"identity\":{\"id\":\"e0211bf1-3" +
            "14d-4998-9fdb-cc43bb2bf0b4\",\"created_at\":\"2015-12-21T10:52:56\",\"type\":0,\"value\":" +
            "\"3051b774@mailinator.com\",\"is_confirmed\":false}},\"private_key\":\"LS0tLS1CRUdJTiBF" +
            "QyBQUklWQVRFIEtFWS0tLS0tCk1JSGFBZ0VCQkVCREN1NzJlcUFDSTh3WlZvQkJOQ3lTMVVKSThYOEFh" +
            "U2YrQXFJaysrdmFOUDdiL0ZUeXVsYVMKN3hBaW5YaVpMbzBMWEFBamI4enpmelgrSlZXL0U1c1BvQXNH" +
            "Q1Nza0F3TUNDQUVCRGFHQmhRT0JnZ0FFZEF2NAo1V2dYYWpEU0VjclhHazFQcFZZNnhDUjFXUzFZNVJn" +
            "bnh4R3FUSTB4dTdrOU54K2k3Y2xFWWhWUXZNSDF3dGlYCmtsSmw2R2FRTHUrMUhVbWJEMkkxdEtQNDJF" +
            "cU1DYlJIZHdLNDk2azZzNkFGVkQ3THZaZXNCYlNDKzF3TXhWL3MKUDlJWmhxTjhxL3hsUVkrN2hPYU92" +
            "TERaYkl4VzZNUHF2TEdiN09RPQotLS0tLUVORCBFQyBQUklWQVRFIEtFWS0tLS0tCg==\"}")]
        public string UnconfirmedPersonalCard {
            get {
                return ((string)(this["UnconfirmedPersonalCard"]));
            }
            set {
                this["UnconfirmedPersonalCard"] = value;
            }
        }
    }
}
