var searchData=
[
  ['client',['Client',['../namespace_virgil_1_1_s_d_k_1_1_client.html',1,'Virgil::SDK']]],
  ['client',['Client',['../namespace_virgil_1_1_s_d_k_1_1_shared_1_1_client.html',1,'Virgil::SDK::Shared']]],
  ['common',['Common',['../namespace_virgil_1_1_s_d_k_1_1_common.html',1,'Virgil::SDK']]],
  ['cryptography',['Cryptography',['../namespace_virgil_1_1_s_d_k_1_1_cryptography.html',1,'Virgil::SDK']]],
  ['device',['Device',['../namespace_virgil_1_1_s_d_k_1_1_device.html',1,'Virgil::SDK']]],
  ['exceptions',['Exceptions',['../namespace_virgil_1_1_s_d_k_1_1_exceptions.html',1,'Virgil::SDK']]],
  ['http',['Http',['../namespace_virgil_1_1_s_d_k_1_1_client_1_1_http.html',1,'Virgil::SDK::Client']]],
  ['virgil_20security_20_2enet_2fc_23_20sdk',['Virgil Security .NET/C# SDK',['../index.html',1,'']]],
  ['sdk',['SDK',['../namespace_virgil_1_1_s_d_k.html',1,'Virgil']]],
  ['shared',['Shared',['../namespace_virgil_1_1_s_d_k_1_1_shared.html',1,'Virgil::SDK']]],
  ['storage',['Storage',['../namespace_virgil_1_1_s_d_k_1_1_storage.html',1,'Virgil::SDK']]],
  ['transferobjects',['TransferObjects',['../namespace_virgil_1_1_s_d_k_1_1_shared_1_1_client_1_1_transfer_objects.html',1,'Virgil::SDK::Shared::Client']]],
  ['validate',['Validate',['../interface_virgil_1_1_s_d_k_1_1_client_1_1_i_card_validator.html#a2e725142e8eb3cfe114523da2c2c87e9',1,'Virgil.SDK.Client.ICardValidator.Validate()'],['../class_virgil_1_1_s_d_k_1_1_common_1_1_card_validator.html#aa1b0c56e77ae9a21b761933b3b86a56a',1,'Virgil.SDK.Common.CardValidator.Validate()']]],
  ['validationoptions',['ValidationOptions',['../class_virgil_1_1_s_d_k_1_1_client_1_1_validation_options.html',1,'Virgil::SDK::Client']]],
  ['value',['Value',['../class_virgil_1_1_s_d_k_1_1_cryptography_1_1_private_key.html#affc9af59ef395f735c0975a6a03ae75d',1,'Virgil.SDK.Cryptography.PrivateKey.Value()'],['../class_virgil_1_1_s_d_k_1_1_identity_validation_token.html#a7de9f3c17ff2921b273c9a4dd40abed8',1,'Virgil.SDK.IdentityValidationToken.Value()']]],
  ['verify',['Verify',['../class_virgil_1_1_s_d_k_1_1_cryptography_1_1_virgil_crypto.html#a2be9381040d811a67bc0bd72eb7921bb',1,'Virgil.SDK.Cryptography.VirgilCrypto.Verify(byte[] data, byte[] signature, IPublicKey signerKey)'],['../class_virgil_1_1_s_d_k_1_1_cryptography_1_1_virgil_crypto.html#a8fc5ae056bcc1843628f19b186084af2',1,'Virgil.SDK.Cryptography.VirgilCrypto.Verify(Stream inputStream, byte[] signature, IPublicKey publicKey)'],['../class_virgil_1_1_s_d_k_1_1_virgil_card.html#a11757be5ab414c06469beb91bc5a1d69',1,'Virgil.SDK.VirgilCard.Verify()']]],
  ['verifyidentityasync',['VerifyIdentityAsync',['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client.html#ae76d0c159270d0cc33f2d029763df6f8',1,'Virgil::SDK::Client::VirgilClient']]],
  ['virgil',['Virgil',['../namespace_virgil.html',1,'']]],
  ['virgilapi',['VirgilApi',['../class_virgil_1_1_s_d_k_1_1_virgil_api.html#a085e4f603c3d4cf840f31e524a6a8a7a',1,'Virgil.SDK.VirgilApi.VirgilApi(string accessToken)'],['../class_virgil_1_1_s_d_k_1_1_virgil_api.html#aee90c4109b1f92a5a24ae17bc9ba6ef0',1,'Virgil.SDK.VirgilApi.VirgilApi()'],['../class_virgil_1_1_s_d_k_1_1_virgil_api.html#af8e71731c5bb2ec9d8eca9ce864a4a94',1,'Virgil.SDK.VirgilApi.VirgilApi(VirgilApiContext context)']]],
  ['virgilapi',['VirgilApi',['../class_virgil_1_1_s_d_k_1_1_virgil_api.html',1,'Virgil::SDK']]],
  ['virgilapicontext',['VirgilApiContext',['../class_virgil_1_1_s_d_k_1_1_virgil_api_context.html',1,'Virgil::SDK']]],
  ['virgilapicontext',['VirgilApiContext',['../class_virgil_1_1_s_d_k_1_1_virgil_api_context.html#a75b86dd81a3408ca8391bd172b90b73e',1,'Virgil::SDK::VirgilApiContext']]],
  ['virgilapiexception',['VirgilApiException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_api_exception.html#af3c38741fa8c41751618f37149815e33',1,'Virgil::SDK::Exceptions::VirgilApiException']]],
  ['virgilapiexception',['VirgilApiException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_api_exception.html',1,'Virgil::SDK::Exceptions']]],
  ['virgilbuffer',['VirgilBuffer',['../class_virgil_1_1_s_d_k_1_1_virgil_buffer.html',1,'Virgil::SDK']]],
  ['virgilcard',['VirgilCard',['../class_virgil_1_1_s_d_k_1_1_virgil_card.html',1,'Virgil::SDK']]],
  ['virgilcardisnotfoundexception',['VirgilCardIsNotFoundException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_card_is_not_found_exception.html',1,'Virgil::SDK::Exceptions']]],
  ['virgilcardisnotfoundexception',['VirgilCardIsNotFoundException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_card_is_not_found_exception.html#aefb1af8f0283881e81f91115f110f801',1,'Virgil::SDK::Exceptions::VirgilCardIsNotFoundException']]],
  ['virgilclient',['VirgilClient',['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client.html',1,'Virgil::SDK::Client']]],
  ['virgilclient',['VirgilClient',['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client.html#a59f011b8224a14039001b4fa144eeff5',1,'Virgil.SDK.Client.VirgilClient.VirgilClient()'],['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client.html#a0bcf781e6a4655a5a025dc0b7a1e14ad',1,'Virgil.SDK.Client.VirgilClient.VirgilClient(string accessToken)'],['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client.html#ac6c43842bd3e03d66eeab548faf7a401',1,'Virgil.SDK.Client.VirgilClient.VirgilClient(VirgilClientParams parameters)']]],
  ['virgilclientexception',['VirgilClientException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_client_exception.html#a11efa6e0d85e1fa8559e36099d39abd2',1,'Virgil::SDK::Exceptions::VirgilClientException']]],
  ['virgilclientexception',['VirgilClientException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_client_exception.html',1,'Virgil::SDK::Exceptions']]],
  ['virgilclientparams',['VirgilClientParams',['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client_params.html',1,'Virgil::SDK::Client']]],
  ['virgilclientparams',['VirgilClientParams',['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client_params.html#a2237fe27b168fba0b9f903dcd0f2e742',1,'Virgil.SDK.Client.VirgilClientParams.VirgilClientParams()'],['../class_virgil_1_1_s_d_k_1_1_client_1_1_virgil_client_params.html#a50adea6dc2715a30bb133e2bab8a7317',1,'Virgil.SDK.Client.VirgilClientParams.VirgilClientParams(string accessToken)']]],
  ['virgilconfigisnotinitializedexception',['VirgilConfigIsNotInitializedException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_config_is_not_initialized_exception.html#a956e49dad8efcb52f85c071ac92ae017',1,'Virgil::SDK::Exceptions::VirgilConfigIsNotInitializedException']]],
  ['virgilconfigisnotinitializedexception',['VirgilConfigIsNotInitializedException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_config_is_not_initialized_exception.html',1,'Virgil::SDK::Exceptions']]],
  ['virgilcrypto',['VirgilCrypto',['../class_virgil_1_1_s_d_k_1_1_cryptography_1_1_virgil_crypto.html#a22f921f283334b052344323b08e3b092',1,'Virgil.SDK.Cryptography.VirgilCrypto.VirgilCrypto(KeyPairType defaultKeyPairType)'],['../class_virgil_1_1_s_d_k_1_1_cryptography_1_1_virgil_crypto.html#addc46484177cc8c08cb38269cee95189',1,'Virgil.SDK.Cryptography.VirgilCrypto.VirgilCrypto()']]],
  ['virgilcrypto',['VirgilCrypto',['../class_virgil_1_1_s_d_k_1_1_cryptography_1_1_virgil_crypto.html',1,'Virgil::SDK::Cryptography']]],
  ['virgilkey',['VirgilKey',['../class_virgil_1_1_s_d_k_1_1_virgil_key.html',1,'Virgil::SDK']]],
  ['virgilkeyisalreadyexistsexception',['VirgilKeyIsAlreadyExistsException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_key_is_already_exists_exception.html',1,'Virgil::SDK::Exceptions']]],
  ['virgilkeyisnotfoundexception',['VirgilKeyIsNotFoundException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_key_is_not_found_exception.html',1,'Virgil::SDK::Exceptions']]],
  ['virgilserviceexception',['VirgilServiceException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_service_exception.html',1,'Virgil::SDK::Exceptions']]],
  ['virgilserviceexception',['VirgilServiceException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_service_exception.html#a70946c578a4bd1dc91cf1b7b2ab8ab76',1,'Virgil.SDK.Exceptions.VirgilServiceException.VirgilServiceException(int errorCode, string errorMessage)'],['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_service_exception.html#abcea22b5a3286774ea7a7beca6dbf884',1,'Virgil.SDK.Exceptions.VirgilServiceException.VirgilServiceException(string message)']]],
  ['virgilserviceprivateservicesexception',['VirgilServicePrivateServicesException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_service_private_services_exception.html#ac4526094d7d499f3075944d9293ab616',1,'Virgil::SDK::Exceptions::VirgilServicePrivateServicesException']]],
  ['virgilserviceprivateservicesexception',['VirgilServicePrivateServicesException',['../class_virgil_1_1_s_d_k_1_1_exceptions_1_1_virgil_service_private_services_exception.html',1,'Virgil::SDK::Exceptions']]]
];
