//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virgil.SDK.PrivateKeys {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Virgil.SDK.PrivateKeys.Localization", typeof(Localization).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application token is not valid exception.
        /// </summary>
        internal static string ExceptionApplicationTokenInvalid {
            get {
                return ResourceManager.GetString("ExceptionApplicationTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container is not found for given credentials.
        /// </summary>
        internal static string ExceptionAuthenticationContainerNotFound {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationContainerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication credentials are not valid.
        /// </summary>
        internal static string ExceptionAuthenticationCredentialsInvalid {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication session token has been expired.
        /// </summary>
        internal static string ExceptionAuthenticationTokenHasExpired {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationTokenHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication session token is not found.
        /// </summary>
        internal static string ExceptionAuthenticationTokenNotFound {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication session token is not valid.
        /// </summary>
        internal static string ExceptionAuthenticationTokenNotValid {
            get {
                return ResourceManager.GetString("ExceptionAuthenticationTokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container already exists.
        /// </summary>
        internal static string ExceptionContainerAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionContainerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container is not valid.
        /// </summary>
        internal static string ExceptionContainerInvalid {
            get {
                return ResourceManager.GetString("ExceptionContainerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container is not found.
        /// </summary>
        internal static string ExceptionContainerNotFound {
            get {
                return ResourceManager.GetString("ExceptionContainerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container password is not valid.
        /// </summary>
        internal static string ExceptionContainerPasswordInvalid {
            get {
                return ResourceManager.GetString("ExceptionContainerPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container password is not specified.
        /// </summary>
        internal static string ExceptionContainerPasswordNotSpecified {
            get {
                return ResourceManager.GetString("ExceptionContainerPasswordNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container type is not valid.
        /// </summary>
        internal static string ExceptionContainerTypeInvalid {
            get {
                return ResourceManager.GetString("ExceptionContainerTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key by given Public key ID already exists.
        /// </summary>
        internal static string ExceptionPrivateKeyAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionPrivateKeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key in not valid.
        /// </summary>
        internal static string ExceptionPrivateKeyInvalid {
            get {
                return ResourceManager.GetString("ExceptionPrivateKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key in not in Base64 format.
        /// </summary>
        internal static string ExceptionPrivateKeyInvalidBase64 {
            get {
                return ResourceManager.GetString("ExceptionPrivateKeyInvalidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key ID is not valid.
        /// </summary>
        internal static string ExceptionPublicKeyIdInvalid {
            get {
                return ResourceManager.GetString("ExceptionPublicKeyIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key ID is not found.
        /// </summary>
        internal static string ExceptionPublicKeyIdNotFound {
            get {
                return ResourceManager.GetString("ExceptionPublicKeyIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request privateKey is not valid.
        /// </summary>
        internal static string ExceptionRequestSignIsNotValid {
            get {
                return ResourceManager.GetString("ExceptionRequestSignIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized error.
        /// </summary>
        internal static string ExceptionUnrecognizedError {
            get {
                return ResourceManager.GetString("ExceptionUnrecognizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification container is not found.
        /// </summary>
        internal static string ExceptionVerificationContainerNotFound {
            get {
                return ResourceManager.GetString("ExceptionVerificationContainerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification token has been expired.
        /// </summary>
        internal static string ExceptionVerificationTokenExpired {
            get {
                return ResourceManager.GetString("ExceptionVerificationTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification token has been expired.
        /// </summary>
        internal static string ExceptionVerificationTokenNotFound {
            get {
                return ResourceManager.GetString("ExceptionVerificationTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification user identity is not valid.
        /// </summary>
        internal static string ExceptionVerificationUserIdentityInvalid {
            get {
                return ResourceManager.GetString("ExceptionVerificationUserIdentityInvalid", resourceCulture);
            }
        }
    }
}
