node('master') { 
    sh 'cp -fr /srv/tomcat/.jenkins/jobs/VirgilCryptoLibBuild/branches/release/lastSuccessful/archive/install/net ./'
    sh 'cp -fr /srv/tomcat/.jenkins/jobs/VirgilCryptoLibBuild/branches/release/lastSuccessful/archive/install/VERSION ./'
    stash includes: '**', name: 'artifacts'
}

node ('build-win8') {
    dir('src') {
        git url: 'https://github.com/VirgilSecurity/virgil-sdk-net.git', branch: 'v3'        
    }
    dir('build') {
        unstash 'artifacts'
    }
    // bat "Powershell.exe -executionpolicy unrestricted -File  Setup.ps1 ${env.NUGET_API_TOKEN} ${env.BUILD_NUMBER}"    
}