namespace Virgil.SDK.Cryptography
{
    using System.Collections.Generic;

    /// <summary>
    /// The <see cref="ICryptoProvider"/> interface provides a set of methods for dealing with 
    /// low-level cryptographic primitives and algorithms. 
    /// </summary>
    public interface ICryptoProvider
    {
        /// <summary>
        /// Encrypt data using the specified AlgorithmIdentifier with the supplied CryptoKey.
        /// </summary>
        /// <param name="clearData">The data to be encrypted.</param>
        /// <param name="recipients">The dictionary of public key recipients.</param>
        /// <returns>
        /// The cipher data generated by the encryption of the clear data as a byte array.
        /// </returns>
        byte[] Encrypt(byte[] clearData, IDictionary<string, byte[]> recipients);
    }
}