namespace Virgil.SDK.Cryptography
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The Virgil Cryptography API provides high level cryptographic operations in applications, such as
    /// signature generation and verification, and encryption and decryption using entities such as 
    /// <see cref="VirgilCard"/> and <see cref="VirgilKey"/>.
    /// </summary>
    public class VirgilCrypto
    {
        private readonly ICryptoProvider cryptoProvider;

        /// <summary>
        /// Initializes a new instance of the <see cref="VirgilCrypto"/> class.
        /// </summary>
        /// <param name="cryptoProvider">The crypto provider.</param>
        public VirgilCrypto(ICryptoProvider cryptoProvider)
        {
            this.cryptoProvider = cryptoProvider;
        }

        /// <summary>
        /// Encrypts the data using 
        /// </summary>
        /// <param name="clearData">The buffer.</param>
        /// <param name="recipients">The list of recipients as an <see cref="IVirgilCard"/> enumeration.</param>
        /// <returns>
        /// The cipherdata generated by the encryption of the cleardata as an <see cref="VirgilBuffer"/>.
        /// </returns>
        public static VirgilBuffer Encrypt(VirgilBuffer clearData, IEnumerable<IVirgilCard> recipients)
        {
            throw new NotImplementedException();
        }
    }
}